### ISSUE TITLE
Can/should we have multiple servers on same port?

### ISSUE THREAD

**Issue by Jgm-h** [th1zan/webserv#2]

**Comment by th1zan** [comment]
**Yes, we can.**

Actually, the flow works like this (from the beginning, long story):

Write a URL in your browser.

The browser queries a DNS server to obtain the IP address associated with the URL.

By default: The browser sends an HTTP request to the IP on port 80 (HTTP) or 443 (HTTPS).

If specified: The browser sends an HTTP request to the IP on the specified port. For example, if you write the URL localhost:8080, the browser queries DNS for the IP.

First, it checks the local DNS (such as /etc/hosts).
You're lucky! "localhost" is indexed by your local DNS and links "localhost" to the IP 127.0.0.1 (which is your web server).
Then, your browser appends the port to the IP before sending the HTTP request (127.0.0.1:8080).
Lucky again! Your web server has a server block with the directive host 8080. This means there is a socket configured to listen on this port.

The browser sends an HTTP request with the "host" header. The "host" in the request corresponds to the server_name directive (which can have multiple server_name values).

If the "host" in the HTTP request matches one of the server_name values, the request is processed by the corresponding server block.
If not, a search is conducted to find the correct server name (i.e., the correct server instance, or server block, or socket).


**So, it is possible to have multiple server names for the same port.**
By the way, I wrote a page on the wiki about that. En français: https://github.com/th1zan/webserv/wiki/Communication-navigateur-et-serveur
