### ISSUE TITLE
[BUG] Fix POST

### ISSUE THREAD

**Issue by Jgm-h** [th1zan/webserv#20]
curl -v -X POST http://localhost:8080/upload/testfile.txt -H "Content-Type: text/plain" --data-binary "This is a simple plain text content."

**Comment by Jgm-h** [comment]
Problem is that the uploadTo variable is empty in the upload location block

**Comment by jannettas** [comment]
I don't know what was wrong, we made some edits and several things were broken at that moment, so we just reset it to my last commit and it was fine after. I confirm POST is fine now
